=== SGroe/vgi-analytics-framework/target/classes/settings/validator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.salzburgresearch.at" 
	xmlns="http://www.salzburgresearch.at"
	elementFormDefault="qualified">
	<xs:element name="settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="general" minOccurs="1" maxOccurs="1" />
				<xs:element ref="analysis" minOccurs="0" maxOccurs="1" />
				<xs:element ref="filterPolygons" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="general">
		<xs:complexType>
			<xs:attribute name="settingName" type="xs:string" use="required" />
			<xs:attribute name="pbfDataFolder" type="xs:string" use="required" />
			<xs:attribute name="readQuadtree" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="false|true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="resultFolder" type="xs:string" use="optional" />
			<xs:attribute name="filterTimestamp" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="analysis">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filterTag" minOccurs="0" maxOccurs="100" />
				<xs:element ref="featureType" minOccurs="1" maxOccurs="100" />
				<xs:element ref="analysisSubject" minOccurs="1" maxOccurs="100" />
				<xs:element ref="actionDefinition" minOccurs="1" maxOccurs="100" />
			</xs:sequence>
			<xs:attribute name="filterElementType" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="UNDEFINED|NODE|WAY|RELATION" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="filterTag" type="xs:string" use="optional" />
			<xs:attribute name="analysisStartDate" type="xs:dateTime" use="optional" />
			<xs:attribute name="analysisEndDate" type="xs:dateTime" use="optional" />
			<xs:attribute name="temporalResolution" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="eternity|century|decade|year|month|day" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="findRelatedOperations" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="false|true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="writeGeometryFiles" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="false|true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="actionTimeBuffer" type="xs:integer" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="filterPolygons">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="polygon" minOccurs="1" maxOccurs="10000" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="polygon">
		<xs:complexType>
			<xs:attribute name="label" type="xs:string" use="required" />
			<xs:attribute name="geometry" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="analysisSubject">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="analysisSetting" minOccurs="0" maxOccurs="100" />
			</xs:sequence>
			<xs:attribute name="name" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="VgiAnalysisBatchGeneral"/>
						<xs:enumeration value="VgiAnalysisBatchContributor"/>
						<xs:enumeration value="VgiAnalysisActionPerType"/>
						<xs:enumeration value="VgiAnalysisOperationPerType"/>
						<xs:enumeration value="VgiAnalysisUserPerAction"/>
						<xs:enumeration value="VgiAnalysisUserPerOperation"/>
						<xs:enumeration value="VgiAnalysisUserPerTags"/>
						<xs:enumeration value="VgiAnalysisActionPerFeatureType"/>
						<xs:enumeration value="VgiAnalysisChangeDetection"/>
						<xs:enumeration value="VgiAnalysisHourOfDay"/>
						<xs:enumeration value="VgiAnalysisTags"/>
						<xs:enumeration value="VgiAnalysisFeatureStability"/>
						<xs:enumeration value="VgiAnalysisActionDetails"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="featureType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filterTag" minOccurs="1" maxOccurs="100" />
				<xs:element ref="property" minOccurs="1" maxOccurs="100" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="geometryType" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="filterTag">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required" />
			<xs:attribute name="dataType" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="analysisSetting">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="actionDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="definitionRule" minOccurs="1" maxOccurs="100" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="actionType" type="xs:string" use="required" />
			<xs:attribute name="geometryType" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="definitionRule">
		<xs:complexType>
			<xs:attribute name="operationType" type="xs:string" use="required" />
			<xs:attribute name="entryPoint" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="YES|NO|IF_FEATURE_TYPE_ADDED|IF_FEATURE_TYPE_REMOVED"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SGroe/vgi-analytics-framework/src/main/resources/settings/settings_winter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<settings
		xmlns="http://www.salzburgresearch.at"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.salzburgresearch.at validator.xsd">
	<general
		settingName="GeneralAnalysis"
		pbfDataFolder="%user.home%\Documents\_d\vgi\data\world_2017_02_winter"
		readQuadtree="false"
		resultFolder="%user.home%\Documents\_d\vgi\results\"
		filterTimestamp="2020-01-01T00:00:00Z" />
		
	<filterTags>
		<includeTag key="landuse" value="winter_sports" />
		<includeTag key="piste:type" value="" />
		<includeTag key="aerialway" value="" />
	</filterTags>
	
	<!-- filterElementType: UNDEFINED, POINT, LINE, RELATION -->
	<!-- temporalResolution: eternity, century, decade, year, month, day -->
	<!-- findRelatedOperations e.g. OP_SPLIT_WAY, OP_MERGE_WAY; very time-consuming -->
	<!-- actionTimeBuffer: 1000*60*60*24=86400000=1 day ; 1000*60*60*12=43200000=12hours -->
	<analysis
		filterElementType="LINE"
		analysisStartDate="2004-01-01T00:00:00Z"
		analysisEndDate="2018-01-01T00:00:00Z"
		temporalResolution="month"
		findRelatedOperations="false"
		writeGeometryFiles="true"
		actionTimeBuffer="43200000">
		<featureType name="piste" geometryType="LineString">
			<includeTag key="piste:type" value="downhill" />
			<property key="piste:type" />
			<property key="name" />
			<property key="ref" />
			<property key="piste:difficulty" />
			<property key="lit" />
			<property key="piste:lit" />
			<property key="start_date" />
			<property key="ele" />
		</featureType>
		<featureType name="aerialway" geometryType="LineString">
			<includeTag key="aerialway" value="" />
			<excludeTag key="aerialway" value="goods" />
			<excludeTag key="aerialway" value="zip_line" />
			<excludeTag key="aerialway" value="canopy" />
			<property key="aerialway" />
			<property key="name" />
			<property key="aerialway:occupancy" />
			<property key="aerialway:capacity" />
			<property key="aerialway:duration" />
			<property key="aerialway:bubble" />
			<property key="aerialway:heating" />
			<property key="start_date" />
			<property key="ele" />
			<property key="usage" />
		</featureType>
		<featureType name="wintersports" geometryType="Polygon">
			<includeTag key="landuse" value="winter_sports" />
			<property key="landuse" />
			<property key="name" />
		</featureType>
		
		<analysisSubject name="VgiAnalysisActionPerType" />
		<analysisSubject name="VgiAnalysisActionPerFeatureType" />
		<analysisSubject name="VgiAnalysisBatchGeneral" />
		<analysisSubject name="VgiAnalysisTags">
			<analysisSetting key="tagKey" value="" />
		</analysisSubject>
		<!-- 
		<analysisSubject name="VgiAnalysisCountry" />
		<analysisSubject name="VgiAnalysisUserPerTags">
			<analysisSetting key="tagKey" value="" />
		</analysisSubject>
		<analysisSubject name="VgiAnalysisFeatureStability" />
		<analysisSubject name="VgiAnalysisOperationPerType" />
		<analysisSubject name="VgiAnalysisUserPerAction">
			<analysisSetting key="mergeActionTypes" value="false" />
		</analysisSubject>
		<analysisSubject name="VgiAnalysisBatchContributor" />
		<analysisSubject name="VgiAnalysisUserPerOperation">
			<analysisSetting key="mergeOperationTypes" value="false" />
		</analysisSubject>
		<analysisSubject name="VgiAnalysisActionDetails">
			<analysisSetting key="includeOperationDetails" value="true" />
		</analysisSubject>
		<analysisSubject name="VgiAnalysisHourOfDay" />-->
		<!-- <analysisSubject name="VgiAnalysisChangeDetection" />-->
		
		<actionDefinition name="AC_CREATE_POINT" actionType="CREATE" geometryType="POINT">
			<definitionRule operationType="OP_RECREATE_NODE" entryPoint="YES" />
			<definitionRule operationType="OP_CREATE_NODE" entryPoint="YES" />
			<definitionRule operationType="OP_ADD_TAG" entryPoint="IF_FEATURE_TYPE_ADDED" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="IF_FEATURE_TYPE_ADDED" />
		</actionDefinition>
		<actionDefinition name="AC_CREATE_LINE" actionType="CREATE" geometryType="LINE">
			<definitionRule operationType="OP_RECREATE_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_CREATE_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_ADD_TAG" entryPoint="IF_FEATURE_TYPE_ADDED" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="IF_FEATURE_TYPE_ADDED" />
			<definitionRule operationType="OP_ADD_NODE" entryPoint="NO" />
		</actionDefinition><!--
		<actionDefinition name="AC_CREATE_RELATION" actionType="CREATE" geometryType="RELATION">
			<definitionRule operationType="OP_RECREATE_RELATION" entryPoint="YES" />
			<definitionRule operationType="OP_CREATE_RELATION" entryPoint="YES" />
			<definitionRule operationType="OP_ADD_TAG" entryPoint="IF_FEATURE_TYPE_ADDED" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="IF_FEATURE_TYPE_ADDED" />
			<definitionRule operationType="OP_ADD_MEMBER" entryPoint="NO" />
		</actionDefinition>-->
		<actionDefinition name="AC_DELETE_POINT" actionType="DELETE" geometryType="POINT">
			<definitionRule operationType="OP_DELETE_NODE" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_TAG" entryPoint="IF_FEATURE_TYPE_REMOVED" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="IF_FEATURE_TYPE_REMOVED" />
		</actionDefinition>
		<actionDefinition name="AC_DELETE_LINE" actionType="DELETE" geometryType="LINE">
			<definitionRule operationType="OP_DELETE_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_TAG" entryPoint="IF_FEATURE_TYPE_REMOVED" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="IF_FEATURE_TYPE_REMOVED" />
			<definitionRule operationType="OP_REMOVE_NODE" entryPoint="NO" />
		</actionDefinition><!--
		<actionDefinition name="AC_DELETE_RELATION" actionType="DELETE" geometryType="RELATION">
			<definitionRule operationType="OP_DELETE_RELATION" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_TAG" entryPoint="IF_FEATURE_TYPE_REMOVED" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="IF_FEATURE_TYPE_REMOVED" />
			<definitionRule operationType="OP_REMOVE_MEMBER" entryPoint="NO" />
		</actionDefinition>-->
		<actionDefinition name="AC_UPDATE_POINT" actionType="UPDATE" geometryType="POINT">
			<definitionRule operationType="OP_ADD_TAG" entryPoint="YES" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_TAG" entryPoint="YES" />
			<definitionRule operationType="OP_MODIFY_COORDINATE" entryPoint="YES" />
		</actionDefinition><!--
		<actionDefinition name="AC_SPLIT_MERGE_LINE" actionType="UPDATE" geometryType="LINE">
			<definitionRule operationType="OP_SPLIT_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_MERGE_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_CREATE_WAY" entryPoint="NO" />
			<definitionRule operationType="OP_ADD_TAG" entryPoint="NO" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="NO" />
			<definitionRule operationType="OP_REMOVE_TAG" entryPoint="NO" />
			<definitionRule operationType="OP_REVERSE_WAY" entryPoint="NO" />
			<definitionRule operationType="OP_ADD_NODE" entryPoint="NO" />
			<definitionRule operationType="OP_REMOVE_NODE" entryPoint="NO" />
			<definitionRule operationType="OP_REORDER_NODE" entryPoint="NO" />
			<definitionRule operationType="OP_MODIFY_WAY_COORDINATE" entryPoint="NO" />
		</actionDefinition>-->
		<actionDefinition name="AC_UPDATE_LINE" actionType="UPDATE" geometryType="LINE">
			<definitionRule operationType="OP_SPLIT_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_MERGE_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_ADD_TAG" entryPoint="YES" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_TAG" entryPoint="YES" />
			<definitionRule operationType="OP_REVERSE_WAY" entryPoint="YES" />
			<definitionRule operationType="OP_ADD_NODE" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_NODE" entryPoint="YES" />
			<definitionRule operationType="OP_REORDER_NODE" entryPoint="YES" />
			<definitionRule operationType="OP_MODIFY_WAY_COORDINATE" entryPoint="YES" />
		</actionDefinition><!--
		<actionDefinition name="AC_UPDATE_RELATION" actionType="UPDATE" geometryType="RELATION">
			<definitionRule operationType="OP_ADD_TAG" entryPoint="YES" />
			<definitionRule operationType="OP_MODIFY_TAG_VALUE" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_TAG" entryPoint="YES" />
			<definitionRule operationType="OP_ADD_MEMBER" entryPoint="YES" />
			<definitionRule operationType="OP_REMOVE_MEMBER" entryPoint="YES" />
			<definitionRule operationType="OP_REORDER_MEMBER" entryPoint="YES" />
			<definitionRule operationType="OP_MODIFY_ROLE" entryPoint="YES" />
		</actionDefinition>-->
	</analysis>
	<filterPolygons>
		<polygon label="StMoritz" geometry="POLYGON((9.771 46.482, 9.771 46.551, 9.860 46.551, 9.860 46.482, 9.771 46.482))" />
	</filterPolygons>
</settings>
